load("@rules_pkg//pkg:mappings.bzl", "pkg_files")

pkg_files(
    name = "prometheus",
    srcs = [
        "prometheus.lua",
    ],
    prefix = "prometheus",
    visibility = ["//visibility:public"],
)
