name: build
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  push:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: bazelisk build --disk_cache=/tmp/bazel-cache -c opt //:graftorio2
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: bazel-bin/*.zip
